name: 'Octo Nudge'
description: 'Sends Slack and/or Discord nudges'
inputs:
  webhooks:
    description: 'A comma separated list of Slack/Discord webhooks to which to send the nudge'
    required: true
  success-color:
    description: 'Hex value of the color for successfull workflow run conclussions'
    required: false
    default: '#228c22'
  failure-color:
    description: 'Hex value of the color for failed workflow run conclussions'
    required: false
    default: '#990f02'
  nudge-blocks:
    description: 'A comma separated list of blocks you want to see in the nudge message. Default: [commit,message]. Blocks will appear in provided order'
    required: false
    default: 'commit,message'
runs:
  using: 'node16'
  main: 'index.js'