name: Build Octo Nudge

on:
  push:
    branches:
    tags:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Set Node.js 16.x
        uses: actions/setup-node@v2.5.1
        with:
          node-version: 16.x

      - name: Install dependencies
        run: npm ci

      - name: Build dist/ directory
        run: npm run prepare

      - name: Push dist/ directory
        run: |
          git add dist/
          git commit -m "[ci] Build the action"
          git status
        