name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm ci
      - run: npm run prepare
      - run: |
          git config --global user.email "ci.bot@githu.com"
          git config --global user.name "bot"
          git commit -a -m "Build dist dir"
          git push origin main